### ISSUE TITLE
DBus file was not found

### ISSUE THREAD

**Issue by 4kihir0** [HoneyPots0/HPomb#5]
When I want to start bombing with SMS, he send me this error message :

Traceback (most recent call last):
  File "core/smcl.py", line 15, in <module>
    import notify2
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/notify2.py", line 39, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

Please, help me

**Comment by HoneyPots0** [comment]
This Error Fix in Version 2020.10 
which is release 10 oct 2020 
thank you
